### ISSUE TITLE
Add NetworkManager support

### ISSUE THREAD

**Issue by lgrawet** [OpenNebula/addon-context-linux#170]
Hi,

The following statement is made in RHEL8 [release notes](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.0_release_notes/index#networking):

> Network scripts are deprecated in Red Hat Enterprise Linux 8 and they are no longer provided by default. The basic installation provides a new version of the ifup and ifdown scripts which call the NetworkManager service through the nmcli tool. In Red Hat Enterprise Linux 8, to run the ifup and the ifdown scripts, NetworkManager must be running.
> 
> Note that custom commands in /sbin/ifup-local, ifdown-pre-local and ifdown-local scripts are not executed.
> 
> If any of these scripts are required, the installation of the deprecated network scripts in the system is still possible with the following command:
> 
> ~]# yum install network-scripts
> The ifup and ifdown scripts link to the installed legacy network scripts.
> 
> Calling the legacy network scripts shows a warning about their deprecation.

Instead of removing NetworkManager and installing deprecated network-scripts, I recommend to simply remove "NM_CONTROLLED=no" statement from network-scripts config files (ifcfg-.*).

Best regards,

Laurent

**Comment by hydro-b** [comment]
Not sure what the correct step(s) are to make this work on CentOS 8. The above mentioned disabling of "NM_CONTROLLED=no" didn't do the trick for me. For the time being, workaround, the latest one-context 5.8.0 el7 do work with the legacy network-scripts though.

**Comment by vholer** [comment]
@hydro-b For the upcoming 5.10 release, there will be new `.el8` package with additional `network-scripts` dependency until we evaluate the better approach. You can already build beta packages from master branch if you need. https://github.com/OpenNebula/addon-context-linux#steps

**Comment by phroton** [comment]
> @hydro-b For the upcoming 5.10 release, there will be new `.el8` package with additional `network-scripts` dependency until we evaluate the better approach. You can already build beta packages from master branch if you need. https://github.com/OpenNebula/addon-context-linux#steps

Is it correct, that you will only remove "NM_CONTROLLED=no" in /etc/one-context.d/loc-10-network and still use the old-style network-scripts?

**Comment by vholer** [comment]
EL8 package will now only install legacy `netwok-scripts` package, nothing more. `NM_CONTROLLED=no` leaves still there.

**Comment by phroton** [comment]
> EL8 package will now only install legacy `netwok-scripts` package, nothing more. `NM_CONTROLLED=no` leaves still there.

Sorry but thats not enough.
NM_CONTROLLED must be removed or set to "yes" in EL8.
If not set to yes, the interface will not come up on boot-time.

**Comment by vholer** [comment]
It should come up on boot, because each interface is put up by the scripts:

https://github.com/OpenNebula/addon-context-linux/blob/3420656fcde3d2a03057f322cd996448f7e51daa/src/etc/one-context.d/loc-10-network%23%23rpm.one#L297

If you don't want to rely on the contextualization scripts later (e.g., you uninstall the contextualization package), it's true that the NetworkManager ignores that interface (because of `NM_CONTROLLED=no`).  To deal with that, it's good to have also  legacy `network` service enabled to finish the activation.

```
$ systemctl enable network
```

But, maybe I'm missing something.

**Comment by phroton** [comment]
@vholer Thank you for the hint. That works for us. :-)

**Comment by vholer** [comment]
I'm converting this issue into native support for NetworkManager controlled and configured interfaces, so that current legacy approach with network-scripts and excluding NM (via `NM_CONTROLLED=no`) will stay as is. Native NM support should work independently on the OS, it will talk to NM over standard api (`nm-cli`?) instead of RH specific files.

**Comment by vholer** [comment]
NM support implemented as part of #227
