### ISSUE TITLE
resolv.conf has no nameservers

### ISSUE THREAD

**Issue by Madko** [OpenNebula/addon-context-linux#81]
Hi,

don't quite understand why, but no nameservers are set in /etc/resolv.conf.
To fix that I have to do:
`cp /etc/one-context.d/loc-11-dns /etc/one-context.d/net-11-dns`

My dns are passed thru context with ETHX_DNS

This is on Fedora 26 server. I can try on CentOS 7.
OpenNebula 5.4 one-context-5.4.0-1.el7.noarch

I think it was working nice with one-context-5.0.x

As far as I understand this might be because one-contextd is run in network type configuration. Which seems fine, but why there is no net-xx-dns ?

Best regards,
Edouard

**Comment by vholer** [comment]
@Madko, do you have the NetworkManager removed from instance?

Fedora isn't tested, I'll try.

**Comment by Madko** [comment]
This is Fedora 26 Server Edition, and indeed I guess NetworkManager is present. I can check that in a few hours. 

Is that a problem to have net-11-dns ?

Before having net-11-dns I tought that was because PEERDNS was no set to "no". And since the loc-11-dns was directly writing to /etc/resolv.conf, I tought NM was overwriting it. I read that in Fedora documentation. But no. Adding PEERDNS=no doesn't change anything. That's how I found that the one-context.d dns script wa not called.

**Comment by vholer** [comment]
I'm using Cloud Base image for the OpenStack:
https://alt.fedoraproject.org/cloud/
contextualized with one-context-5.4.0-1.el7.noarch and it works for me as expected, the resolver configuration is there. I had to disable SELinux only.

> Is that a problem to have net-11-dns ?
Hmm, problem is that loc-* scripts should prepare everything necessary for the networking. That's why it's in loc-*. On network target, many other system services depend and we can't force net-* scripts to start right after the networking and before any other service.

Can you please check the journal, that the loc-11-dns is started at all and doesn't fail? Can you please check once again the NetworkManager is gone and SELinux is (at least) permissive or disabled.

For the start, I'm going to add obsolete on the NetworkManager into the rpm.

**Comment by Madko** [comment]
```
juil. 27 18:42:15 f26server1 one-contextd[1117]: Script loc-11-dns: Starting ...
juil. 27 18:42:15 f26server1 one-contextd[1136]: Script loc-11-dns: Finished with exit code 0
```
loc-11-dns is started just before NetworkManager. If I add
```
cp /etc/resolv.conf /tmp
```
at the end of loc-11-dns, /tmp/resolv.conf is empty. Will check if it's related to SELinux.

The workaround to cp loc-11-dns to net-11-dns is already pretty good since it doesn't break anything (ie works with NetworkManager and SELinux). But I'd like to understand why just loc-11-dns is producing an empty resolv.conf.

**Comment by Madko** [comment]
In fact, it seems that just by removing the symlink /etc/resolv.conf made by NetworkManager (I don't know when) is even better. This is why loc-11-dns was doing anything here. This link was certainly created during installation or first boot by NM, before having NM_CONTROLLED=no.

Everything works fine now, fully compatible with NM, and, very important for security, SELinux.

btw, imho, if you remove NetworkManager package (by obsoleting it), it will also remove a lot of things that make the Fedora server edition what it is (cockpit, fedora-server-release etc), and it will make it more like the cloud edition. And, you have to hope that it will also remove the /etc/resolv.conf symlink

Sorry for the noise, and thanks for your help
