### ISSUE TITLE
Adding SLES

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/addon-context-linux#98]
Hi,

I'd like to do what's needed to put SLES on the support matrix.
I need info which is the minimal set of context scripts that need to be working, and which tests to run.
I'm looking to cover SLES11 and SLES12.

**Comment by FlorianHeigl** [comment]
Hi,

thanks, those infos help me quite a bit.

As for SLES. a little reality check:
Currently neither is tested to work well, neither is supported. (I want to help fix that)
SLES12 installed base is currently still _irrelevant_ (5% of SLES installs based of what I see)
SLES11 has 100's of thousands of installs.


As for shops running SLES11 or SLES12:
* Are they running on ONE? No
* Are they running OpenStack? Yes
*  Is it because ONE sucked at consistent OS support for years, which discouraged SUSE pushing ONE? It might just be because that is exactly what happened?

So, no it's not a good idea to not support a major distro that is currently widely used because it will go EOL _next_ year. Lets not go down that path _again_.

I just wanna make sure the context stuff works, for the marketplace a 42.2/42.3 OpenSUSE + Tumbleweed will be the better choice since those have public repos.
I agree on closed distros, at the moment, with OS Security being as it is now we can't in good conscience provide images with flawed kernels and no update.

For the daily tests though an image without updates could be OK?
After reading once more, 3) is what I wanna make sure to be fine.

**Comment by vholer** [comment]
Hi Florian,

> As for SLES. a little reality check:
> Currently neither is tested to work well, neither is supported. (I want to help fix that)
> SLES12 installed base is currently still irrelevant (5% of SLES installs based of what I see)
> SLES11 has 100's of thousands of installs.
>
> As for shops running SLES11 or SLES12:
>
> Are they running on ONE? No
> Are they running OpenStack? Yes
> Is it because ONE sucked at consistent OS support for years, which discouraged SUSE pushing ONE?
> => It might just be the reason, because that is exactly what happened?
>
> So, no it's not a good idea to not support a major distro that is currently widely used because it will go EOL next year. Lets not go down that path again.

hmmm, I gave just a realistic point of view what's feasible and what makes sense for the future. I would really love to see support for all the systems I have on my mind and I hope you see the things are improving, but the resources are limited and we have to make compromises.

> I just wanna make sure the context stuff works, for the marketplace a 42.2/42.3 OpenSUSE + Tumbleweed will be the better choice since those have public repos.

42.3 is OK and things subject to the testing are working.

> For the daily tests though an image without updates could be OK?
> After reading once more, 3) is what I wanna make sure to be fine.

Yes, such image is OK.

Anyway, the repository is public and any user contribution improving the project is welcome. If I see the new platform support emerging, I'll take care of the rest (image/CI) so that **we don't lose it again**. (that's the approach we took with Fedora, Devuan, or OpenSUSE). If you have serious interest in having SLES supported, please consider checking the current suse contextualization package on selected SLES target(s) and propose necessary changes. The easiest is to start with SLES12. We can update in this issue.

Best regards,
Vlastimil

**Comment by FlorianHeigl** [comment]
Thanks, in case that wasn't clear: yes I have strong interest in getting it support, and yes I'll do all stuff that's needed to get there.
I just needed a checklist to work from, and I think I can "grep" that from what you wrote.

**Comment by vholer** [comment]
SLES 12 SP3 was added into the support matrix. Closing.
